spring.datasource.url=jdbc:postgresql://localhost:5432/agricultura
spring.datasource.username=postgres
spring.datasource.password=p0rtugas


springdoc.swagger-ui.path=/swagger
springdoc.api-docs.path=/api-docs

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


server.port=8081